### PR TITLE
Add Sponsor Variant

### PR DESCRIPTION
**Pull request by mathiash98**
## Phone:

image

## Desktop

image

Logo is fetched from https://github.com/varianter/dokument-mal/blob/5a8fcbad5ed10d8fa71de4264b38ac85d52e2747/assets/logo.svg

### CODE REVIEW

**Comment by KWaloen** [comment]
Variant is a bit hard to read no? Would it help to put a white outline on the logo as with Kantega?

**Comment by mathiash98** [comment]
> Variant is a bit hard to read no? Would it help to put a white outline on the logo as with Kantega?

Yep agree, seems like we should have a white background on the full sponsors-container area. And switch the NAV logo to the red one

**Comment by timharek** [comment]
What if the sponsors-section had a white background? That would solve the visibility issue for all of the logos.

**Comment by mathiash98** [comment]
Changed background to the white color we use on text

image

**Review by timharek — APPROVED** [review]
LGTM 😎

**Pull request merged**
